### ISSUE TITLE
Example from README.rst does not work

### ISSUE THREAD

**Issue by pganelin** [zbrookle/sql_to_ibis#69]
I got the following error when I tried to execute the code as is

```
Traceback (most recent call last):
  File "/Users/pavel/Projects/sql_to_ibis/mytest.py", line 1, in <module>
    import ibis.pandas.api
ModuleNotFoundError: No module named 'ibis.pandas'
```

After I adjusted ibis packages

```
import ibis
import pandas
import sql_to_ibis

df = pandas.DataFrame({"column1": [1, 2, 3], "column2": ["4", "5", "6"]})
ibis_table = ibis.backends.pandas.from_dataframe(
    df, name="my_table", client=ibis.backends.pandas.PandasClient({})
)
sql_to_ibis.register_temp_table(ibis_table, "my_table")
sql_to_ibis.query(
    "select column1, cast(column2 as integer) + 1 as my_col2 from my_table"
).execute()
```

I got the following error:

```
Traceback (most recent call last):
  File "~/miniconda3/envs/sql_to_ibis/lib/python3.9/site-packages/lark/lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "~/miniconda3/envs/sql_to_ibis/lib/python3.9/site-packages/lark/lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for 'e' at line 1 col 36

select column1, cast(column2 as integer) + 1 as my_col2 from my_table
                                   ^

Expecting: {'RPAR'}

Previous tokens: Token(TYPENAME, 'int')
```

**Comment by zbrookle** [comment]
Good catch! That was actually a typo, it should've actually been `int`, not `integer`. I'm going to update to support `integer` as well though, since certain sql dialect do use that
